
@api = http://localhost:4000/api/v1

@extension = "https://marketplace.visualstudio.com/items?itemName=humao.rest-client"

### Obtener todos los productos
GET  {{api}}/products

### Obtener numero de productos totales
GET  {{api}}/products/count
 
###  Crear un producto
POST {{api}}/products
Content-Type: application/json

{
    "name": "Tablet", 
    "description": "Product 1 description",
    "quantity": 10
}
 
### Obtener un producto
GET  {{api}}/products/1

###  Eliminar un producto
DELETE {{api}}/products/5


###  Actualizar un producto
PUT {{api}}/products/4
Content-Type: application/json

{
    "name": "Tablet", 
    "description": "Tableta Xiaomi",
    "quantity": 50
}